openapi: 3.1.0
info:
  title: Sourcify Ethereum Function, Event, and Error Signatures API
  description: API for Ethereum function, event, and error signatures lookup, search, and statistics
  version: 1.0.0
  license:
    name: MIT
    url: https://github.com/argotorg/sourcify/blob/master/LICENSE
  contact:
    name: Sourcify
    url: "https://sourcify.dev"
    email: hello@sourcify.dev
servers:
  - url: https://api.4byte.sourcify.dev
    description: Production server
  - url: https://api.4byte.staging.sourcify.dev
    description: Staging server
  - url: http://localhost:4444
    description: Local development server address on default port 4444.

paths:
  /signature-database/v1/lookup:
    get:
      summary: Lookup signatures
      description: Look up one or more function or event signatures by hash
      tags:
        - Signature Database
      parameters:
        - in: query
          name: function
          required: false
          description: A comma-delimited list of function or error hashes with leading 0x prefix. Since the original openchain.xyz API didn't support error signatures, we treat error signatures as function signatures. They are both 4 byte hashes.
          schema:
            type: string
          allowReserved: true
        - in: query
          name: event
          required: false
          description: A comma-delimited list of event hashes with leading 0x prefix
          schema:
            type: string
          allowReserved: true
        - in: query
          name: filter
          required: false
          description: Whether or not to filter out junk results
          schema:
            type: boolean
            default: true
      responses:
        "200":
          description: The resulting signatures
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  result:
                    $ref: "#/components/schemas/SignatureResponse"
              example:
                ok: true
                result:
                  function:
                    "0xa9059cbb":
                      - name: "transfer(address,uint256)"
                        filtered: false
                        hasVerifiedContract: true
                    "0x095ea7b3":
                      - name: "approve(address,uint256)"
                        filtered: false
                        hasVerifiedContract: true
                  event:
                    "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef":
                      - name: "Transfer(address,address,uint256)"
                        filtered: false
                        hasVerifiedContract: true
                    "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925":
                      - name: "Approval(address,address,uint256)"
                        filtered: false
                        hasVerifiedContract: true

  /signature-database/v1/search:
    get:
      summary: Search signatures
      description: Search signatures by name (case sensitive) with wildcards, limited to the first 100 unordered results
      tags:
        - Signature Database
      parameters:
        - in: query
          name: query
          required: true
          description: The name of the function to search for. Case sensitive. Use '*' and '?' for wildcards.
          schema:
            type: string
          allowReserved: true
        - in: query
          name: filter
          required: false
          description: Whether or not to filter out junk results
          schema:
            type: boolean
            default: true
          allowReserved: true
      responses:
        "200":
          description: The resulting signatures. Note that error signatures are treated as function signatures.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  result:
                    $ref: "#/components/schemas/SignatureResponse"
              example:
                ok: true
                result:
                  function:
                    "0xa9059cbb":
                      - name: "transfer(address,uint256)"
                        filtered: false
                        hasVerifiedContract: true
                      - name: "transferToken(address,uint256)"
                        filtered: true
                        hasVerifiedContract: false
                  event:
                    "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef":
                      - name: "Transfer(address,address,uint256)"
                        filtered: false
                        hasVerifiedContract: true

  /signature-database/v1/stats:
    get:
      summary: Show database stats
      description: function, event and error fields show the number of signatures that are associated with a verified contract and the respective type. unknown shows the number of signatures that are not associated with a verified contract, hence no type can be assigned. total shows the total number of signatures in the database.
      tags:
        - Signature Database
      responses:
        "200":
          description: The status of the import
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  result:
                    type: object
                    properties:
                      count:
                        type: object
                        properties:
                          function:
                            type: number
                          event:
                            type: number
                          error:
                            type: number
                          unknown:
                            type: number
                          total:
                            type: number
              example:
                ok: true
                result:
                  count:
                    function: 125847
                    event: 8329
                    error: 2156
                    unknown: 15432
                    total: 151764
  /health:
    get:
      summary: Check server health
      description: Check if the server is running
      responses:
        "200":
          description: The server is running
          content:
            text/plain:
              schema:
                type: string
              example:
                Alive and kicking!
        "500":
          description: Error checking health
          content:
            text/plain:
              schema:
                type: string
              example:
                Error checking database health

components:
  schemas:
    SignatureResponse:
      properties:
        function:
          additionalProperties:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                filtered:
                  type: boolean
                hasVerifiedContract:
                  type: boolean
        event:
          additionalProperties:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                filtered:
                  type: boolean
                hasVerifiedContract:
                  type: boolean
